### ISSUE TITLE
Multiple paths result in multiple widgets that could be unwanted

### ISSUE THREAD

**Issue by KittyKatt** [uatec/homepagesidecar#47]
Hello! I've recently rolled this out to my k8s cluster and I'm noticing something a little annoying (at least for me). Every ingress that has multiple paths will result in multiple of the same widget (just with a number appended to the name). While this might be helpful in some cases, I would think that in most it's not the desired behavior. Take, for instance, my media domain's ingress (stripped down to just radarr and sonarr so no one has to read that text wall):

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-mediaserver
  annotations:
    homepagesc.neutrino.io/appName: Radarr
    homepagesc.neutrino.io/group: Media
    homepagesc.neutrino.io/healthCheck: http://radarr.mediaserver.svc.cluster.local:7878/
    homepagesc.neutrino.io/icon: radarr.png
spec:
  rules:
    - host: beep.boop.com
      http:
        paths:
          - path: /radarr
            pathType: Prefix
            backend:
              service:
                name: radarr
                port:
                  number: 7878
          - path: /sonarr
            pathType: Prefix
            backend:
              service:
                name: sonarr
                port:
                  number: 8989
          - path: /backend1
            pathType: Prefix
            backend:
              service:
                name: backend1
                port:
                  number: 9000
```

I like having my media services underneath one domain so I don't have a billion subdomains sitting around. However, each of these show up as just another "Mediaserver-{N}" for the last three path rules. I also cannot control the paths individually, so I have to settle for only having one widget type, one widget name, and one widget icon for all paths underneath the same Ingress. I have a couple of Ingress resources that also just have separate paths for an additional backend service for a given Prefix. I don't really want to have that on Homepage, just one of the multiple paths representing the frontend. A finer grained control around multiple paths would be ideal.

Without knowing anything nearly anything about Go and how hard this might be, I have this proposal to halfheartedly offer:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-mediaserver
  annotations:
    homepagesc.neutrino.io/appName: Radarr
    homepagesc.neutrino.io/group: Media
    homepagesc.neutrino.io/healthCheck: http://radarr.mediaserver.svc.cluster.local:7878/
    homepagesc.neutrino.io/icon: radarr.png
    homepagesc.neutrino.io/path1.appName: Sonarr
    homepagesc.neutrino.io/path1.group: Media
    homepagesc.neutrino.io/path1.healthCheck: http://sonarr.mediaserver.svc.cluster.local:9696/
    homepagesc.neutrino.io/path1.icon: sonarr.png
    homepagesc.neutrino.io/path3.enable: false
```

This might not be the best format, but hopefully the intention comes across clear. I really am quite enjoying this, btw. This has really helped me get my services under control in Homepage. Thanks for all of the hard work.

**Comment by scme0** [comment]
Hi there, I came across this repo over the last week or two and noticed that it doesn't look to be actively maintained. I've forked the repo and made some changes that I needed including something similar to your suggestion above. If you want to use my fork, you can find it here: https://github.com/scme0/homepagesc

The way the mutliple path handling works is that you can specify the annotations for individual paths with the following format: `homepagesc.io/<service_name>_<port_number>_<annotation_label>`

Ingress objects with a single host/path should use the original annotations.

Note that I've changed the base of the annotation to `homepagesc.io` for brevity.

For instance your example:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-mediaserver
  annotations:
    homepagesc.io/radarr_7878_appName: Radarr
    homepagesc.io/radarr_7878_group: Media
    homepagesc.io/radarr_7878_healthCheck: http://radarr.mediaserver.svc.cluster.local:7878/
    homepagesc.io/radarr_7878_icon: radarr.png
    homepagesc.io/sonarr_8989_enable: 'false'
    homepagesc.io/backend1_9000_enable: 'false'
spec:
  rules:
    - host: beep.boop.com
      http:
        paths:
          - path: /radarr
            pathType: Prefix
            backend:
              service:
                name: radarr
                port:
                  number: 7878
          - path: /sonarr
            pathType: Prefix
            backend:
              service:
                name: sonarr
                port:
                  number: 8989
          - path: /backend1
            pathType: Prefix
            backend:
              service:
                name: backend1
                port:
                  number: 9000
```
